CREATE TABLE notification_configuration (
    id BIGINT PRIMARY KEY,
    channel VARCHAR(30) NOT NULL,
    provider VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    reference_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT uk_notification_channel UNIQUE (channel),
    CONSTRAINT chk_notification_channel
        CHECK (channel IN ('EMAIL', 'SMS', 'WHATSAPP'))
);


-------------------------

CREATE TABLE platform_template (
    template_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name VARCHAR(100) NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    channel VARCHAR(50) NOT NULL,
    template_subject VARCHAR(255) NOT NULL,
    template_body TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_platform_template_event
        UNIQUE (event_type)
);


